# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - connectomics

#defaults:
#  - override hydra/launcher: joblib
eval_only: False
train:
  # reproducibility
  deterministic: False
  random_seed: 42

  # training

  pl_trainer:
    fast_dev_run: False # Enable this for debug purposes
    # gpus: 8
    tpu_cores: 1
    precision: bf16
    max_steps: 60000  # 30000
    # accumulate_grad_batches: 1
    num_sanity_val_steps: 0
    gradient_clip_val: 10000000.0  # 10.

  monitor_metric: 'val_loss'
  monitor_metric_mode: 'min'

  early_stopping:
    patience: 42
    verbose: False

  model_checkpoints:
    save_top_k: 1
    verbose: False

# TPU Tensor Dimension Rules:
# The total batch size should be a multiple of 64 (8 per TPU core), and feature dimension sizes should be a multiple of 128.
# The total batch size should be a multiple of 1024 (128 per TPU core), and feature dimension sizes should be a multiple of 8.
# Using a batch size of 1024 and feature dimensions that are a multiple of 128 results in the best efficiency, although this may not be possible for all models.

model:
  _target_: src.pl_modules.model.MyModel
  name: ResidualUNet3D
  loss: src.pl_modules.losses.bce
  loss_weights: [0.41164063, 8.16566361, 2.23098494]  # [1, 1, 1, 1, 4.76, 1]  # Set to False to not have weights
  ckpt: False
  # ckpt: /cifs/data/tserre/CLPS_Serre_Lab/projects/prj_connectomics/contlearn/checkpoints/epoch=51-step=3327.ckpt
  in_channels: 2  # Image/Membrane inputs
  out_channels: 3  # noqa Must match the max of the dataset. TODO: get this automatically via iterpolation in omegaconf.
  force_2d: False  # Use a 2d model
  plot_argmax: True  # Plot the argmax prediction per voxel on tensorboard

data:
  token: UTUOQJvbbyRFbD_NSnTMig
  scale: [5, 5, 50]
  annotation_type: "nml"  # nml/volumetric/or "???"
  annotation_size: [60, 60, 7]  # x/y/z
  cube_size: [12, 128, 128]  # After transpose if requested. This is the cube size for the dataset  # noqa
  label_transpose_xyz_zyx: [2, 0, 1]
  image_transpose_xyz_zyx: False
  image_downsample: False  # [1, 4.114, 4.114]
  image_layer_name: "images"  # Depreciated
  annotation_path: https://webknossos.org/annotations/Explorational/61d2f118010000ba00ed3a8a
  image_path: gs://serrelab/connectomics/npy/synapse/110629_k0725_mag1_x0_y0_z0.npy
  wkdataset: "https://webknossos.org/datasets/4fd6473e68256c0a/W-Q_x0_y0_z0_2022-01-02_00-43-18"  # set to "???" if not using
  datamodule:
    _target_: src.pl_data.datamodule.MyDataModule
    val_percentage: 0.0
    use_train_dataset: Celltype_Prediction
    use_val_dataset: Celltype_Prediction
    datasets:
      Celltype_Prediction:
        train:
          _target_: src.pl_data.dataset.Volumetric
          train: True
          path: "${data.image_path}"
          # path: gs://serrelab/connectomics/tfrecords/celltype/cell_type_10_64_15.tfrecords_train.tfrecords
          # len: 97
          len: 128
          shape: "${data.cube_size}"
          trim_dims: [[0, 384], [0, 384], [340, 768]]
          force_2d: "${model.force_2d}"
          selected_label: {1: 1, 2: 1, 3: 0, 4: 0, 5: 2, 6: 1}
          # ['AC', 'BC', 'Clear', 'Label', 'Muller', 'RGC']
        val:
          _target_: src.pl_data.dataset.Volumetric
          train: False
          # path: gs://serrelab/connectomics/npy/celltype/cells_1.npz
          path: "${data.image_path}"
          # path: gs://serrelab/connectomics/tfrecords/celltype/cell_type_10_64_15.tfrecords_val.tfrecords
          # len: 11
          len: 10
          shape: "${data.cube_size}"
          # trim_dims: [[34, 52], [156, 384], [156, 384]]
          trim_dims: [[140, 180], [0, 384], [0, 340]]
          force_2d: "${model.force_2d}"
          selected_label: {1: 1, 2: 1, 3: 0, 4: 0, 5: 2, 6: 1}
        test:
          _target_: src.pl_data.dataset.VolumetricTF
          train: False
          # path: gs://serrelab/connectomics/tfrecords/celltype/cell_type_10_64_15.tfrecords_val.tfrecords
          path: "${data.image_path}"
          len: 11
          trim_dims: [[140, 180], [0, 384], [0, 340]]
          force_2d: "${model.force_2d}"
          selected_label: {1: 1, 2: 1, 3: 0, 4: 0, 5: 2, 6: 1}

    num_workers:
      train: 48
      val: 48
      test: 1

    batch_size:
      train: ${mult:8,2}
      val: ${mult:8,2}
      test: ${mult:8,2}

metric:
  name: F1
  _target_: torchmetrics.F1  # src.pl_modules.losses.no_loss
  is_function: True

optim:
  optimizer:
    #  Adam-oriented deep learning
    _target_: torch.optim.Adam
    #  These are all default parameters for the Adam optimizer
    lr: 1e-3  # 0.001
    betas: [ 0.9, 0.999 ]
    eps: 1e-08
    # weight_decay: 1e-7

  use_lr_scheduler: False
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 0 # min value for the lr
    last_epoch: -1

hydra:
  run:
    dir: results/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: gs://serrelab/connectomics/results/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: results/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
    # dir: gs://serrelab/connectomics/results/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread

logging:
  n_elements_to_log: 3  # Set to 16 if tpu=1
  log_every_n_steps: 8

  # log frequency
  val_check_interval: 1.  # Float is epochs, int is steps
  # progress_bar_refresh_rate: 20

  wandb:
    project: cont-learn
    entity: serrelab

    watch:
      log: 'all'
      log_freq: 1

  lr_monitor:
    logging_interval: "step"
    log_momentum: False

